### ISSUE TITLE
Moons Tile changes

### ISSUE THREAD

**Issue by zombJules** [TrevorMDev/tile-packs#43]
I notice that the moon tiles in Eclipse Moon changed and half of them aren't visible any more.

**Comment by TrevorMDev** [comment]
This was intentional. The tiles around the outside edge were very noisy, and walking is a much better method than running every few tiles.

If you want the original tiles back, you can import them as a custom pack.

[{"regionId":5782,"regionX":4,"regionY":32,"z":0,"color":"#FFFF0043","label":"Slash Boss"},{"regionId":5526,"regionX":47,"regionY":29,"z":0,"color":"#FFF2E836","label":"After tigers"},{"regionId":5526,"regionX":45,"regionY":31,"z":0,"color":"#FFF2E836","label":"1"},{"regionId":5526,"regionX":45,"regionY":33,"z":0,"color":"#FFF2E836","label":"2"},{"regionId":5526,"regionX":47,"regionY":35,"z":0,"color":"#FFF2E836","label":"3"},{"regionId":5526,"regionX":51,"regionY":33,"z":0,"color":"#FFF2E836","label":"1"},{"regionId":5526,"regionX":51,"regionY":31,"z":0,"color":"#FFF2E836","label":"2"},{"regionId":5526,"regionX":49,"regionY":29,"z":0,"color":"#FFF2E836","label":"3"},{"regionId":5526,"regionX":49,"regionY":35,"z":0,"color":"#FFF2E836","label":"After Rain"},{"regionId":5782,"regionX":32,"regionY":59,"z":0,"color":"#FF00B8D4","label":"crush Boss"},{"regionId":5783,"regionX":31,"regionY":13,"z":0,"color":"#FFF2E836","label":"After tornade"},{"regionId":5783,"regionX":29,"regionY":15,"z":0,"color":"#FFF2E836","label":"1"},{"regionId":5783,"regionX":29,"regionY":17,"z":0,"color":"#FFF2E836","label":"2"},{"regionId":5783,"regionX":31,"regionY":19,"z":0,"color":"#FFF2E836","label":"3"},{"regionId":5783,"regionX":35,"regionY":17,"z":0,"color":"#FFF2E836","label":"1"},{"regionId":5783,"regionX":35,"regionY":15,"z":0,"color":"#FFF2E836","label":"2"},{"regionId":5783,"regionX":33,"regionY":13,"z":0,"color":"#FFF2E836","label":"3"},{"regionId":5783,"regionX":33,"regionY":19,"z":0,"color":"#FFF2E836","label":"After Frozen Weapons"},{"regionId":5782,"regionX":59,"regionY":32,"z":0,"color":"#FFFF9A00","label":"Stab Boss"},{"regionId":6038,"regionX":11,"regionY":37,"z":0,"color":"#FFF2E836"},{"regionId":6038,"regionX":15,"regionY":29,"z":0,"color":"#FFF2E836","label":"After Orbit"},{"regionId":6038,"regionX":11,"regionY":34,"z":0,"color":"#FFF2E836"},{"regionId":6038,"regionX":11,"regionY":30,"z":0,"color":"#FFF2E836"},{"regionId":6038,"regionX":14,"regionY":37,"z":0,"color":"#FFF2E836"},{"regionId":6038,"regionX":18,"regionY":37,"z":0,"color":"#FFF2E836"},{"regionId":6038,"regionX":21,"regionY":34,"z":0,"color":"#FFF2E836"},{"regionId":6038,"regionX":21,"regionY":30,"z":0,"color":"#FFF2E836"},{"regionId":6038,"regionX":18,"regionY":27,"z":0,"color":"#FFF2E836"},{"regionId":6038,"regionX":14,"regionY":27,"z":0,"color":"#FFF2E836"},{"regionId":6038,"regionX":21,"regionY":37,"z":0,"color":"#FFF2E836"},{"regionId":6038,"regionX":21,"regionY":27,"z":0,"color":"#FFF2E836"},{"regionId":6038,"regionX":11,"regionY":27,"z":0,"color":"#FFF2E836"},{"regionId":6038,"regionX":17,"regionY":35,"z":0,"color":"#FFF2E836","label":"After WhackAMole"},{"regionId":6038,"regionX":19,"regionY":33,"z":0,"color":"#FFF2E836","label":"1"},{"regionId":6038,"regionX":19,"regionY":31,"z":0,"color":"#FFF2E836","label":"2"},{"regionId":6038,"regionX":17,"regionY":29,"z":0,"color":"#FFF2E836","label":"3"},{"regionId":6038,"regionX":13,"regionY":31,"z":0,"color":"#FFF2E836","label":"1"},{"regionId":6038,"regionX":13,"regionY":33,"z":0,"color":"#FFF2E836","label":"2"},{"regionId":6038,"regionX":15,"regionY":35,"z":0,"color":"#FFF2E836","label":"3"},{"regionId":6038,"regionX":16,"regionY":32,"z":0,"color":"#FFF2E836","label":"Whack a Mole"}]
